# Generated by Django 5.2.10 on 2026-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SuperAdmin'), (2, 'SubAdmin'), (3, 'Manager'), (4, 'Student')], default=3, null=True),
        ),
    ]
