# Generated by Django 5.2.10 on 2026-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
