# Generated by Django 5.2.10 on 2026-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SuperAdmin'), (2, 'SubAdmin'), (3, 'Manager'), (4, 'Student'), (5, 'Other')], default=3, null=True),
        ),
    ]
