# Generated by Django 5.2.10 on 2026-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SuperAdmin'), (2, 'SubAdmin'), (3, 'Manager'), (4, 'Student'), (5, 'Other'), (6, 'Efos'), (7, 'Vsl')], default=3, null=True),
        ),
    ]
