# Generated by Django 5.2.10 on 2026-05-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee_waiver_category',
            field=models.CharField(default='No Waiver', max_length=200),
        ),
    ]
