# Generated by Django 5.2.10 on 2026-05-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_managefreereferal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managereferal',
            name='referral_code',
            field=models.CharField(max_length=50),
        ),
    ]
