# Generated by Django 5.2.10 on 2026-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_managereferal_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='managefreereferal',
            name='code_length',
            field=models.IntegerField(default=20),
        ),
    ]
