# Generated by Django 5.2.10 on 2026-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_managefreereferal_non_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SuperAdmin'), (2, 'SubAdmin'), (3, 'Manager'), (4, 'Student'), (5, 'Other'), (6, 'Efos'), (7, 'Vsl'), (8, 'AffliateOne'), (9, 'AffliateTwo'), (10, 'AffliateThree'), (11, 'AffliateFour'), (12, 'AffliateFive'), (13, 'GCCARC')], default=3, null=True),
        ),
    ]
