# Generated by Django 5.2.10 on 2026-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_managelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='managelogin',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
