# Generated by Django 5.2.10 on 2026-07-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_manageloginform_managestudentextradetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SuperAdmin'), (2, 'SubAdmin'), (3, 'Manager'), (4, 'Student'), (5, 'Other'), (6, 'Efos'), (7, 'Vsl'), (8, 'AffliateOne'), (9, 'AffliateTwo'), (10, 'AffliateThree'), (11, 'AffliateFour'), (12, 'AffliateFive'), (13, 'AffliateSix'), (14, 'AffliateSeven'), (15, 'EAWebsite')], default=3, null=True),
        ),
    ]
