# Generated by Django 5.2.10 on 2026-01-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('graduation_program', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_program_other', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_status', models.CharField(blank=True, max_length=255, null=True)),
                ('current_cgpa', models.CharField(blank=True, max_length=255, null=True)),
                ('first_division', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_enquiries',
            },
        ),
    ]
