# Generated by Django 5.2.10 on 2026-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='form_type',
            field=models.IntegerField(choices=[(1, 'Payment'), (2, 'Dossier')], default=1),
        ),
    ]
