# Generated by Django 5.2.10 on 2026-01-23 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('document_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('gcs_path', models.TextField()),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_documents',
            },
        ),
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('father_email', models.CharField(blank=True, max_length=150, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_email', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('class10_year', models.IntegerField(blank=True, null=True)),
                ('class10_score', models.FloatField(blank=True, null=True)),
                ('class12_year', models.IntegerField(blank=True, null=True)),
                ('class12_score', models.FloatField(blank=True, null=True)),
                ('medium_of_instruction', models.CharField(blank=True, max_length=50, null=True)),
                ('medium_other', models.CharField(blank=True, max_length=100, null=True)),
                ('ug_status', models.CharField(blank=True, max_length=20, null=True)),
                ('first_division', models.BooleanField(blank=True, null=True)),
                ('ug_cgpa', models.FloatField(blank=True, null=True)),
                ('ug_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_exists', models.BooleanField(blank=True, null=True)),
                ('pg_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_other', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('work_experience', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students_data',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentsdata')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
