# Generated by Django 5.2.10 on 2026-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_payments_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='form_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
