# Generated by Django 5.1.4 on 2026-01-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentdocuments_studentsdata_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('institution_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('teaching_experience', models.CharField(max_length=50)),
                ('industrial_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_qualification', models.CharField(max_length=255)),
                ('motivation', models.TextField()),
                ('support_activities', models.JSONField()),
                ('student_reach', models.CharField(max_length=255)),
                ('consent', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campus_faculty',
            },
        ),
        migrations.CreateModel(
            name='CampusStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('college_name', models.CharField(max_length=255)),
                ('program_of_study', models.CharField(max_length=255)),
                ('program_other', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(max_length=255)),
                ('student_body_member', models.CharField(max_length=255)),
                ('campus_ambassador_history', models.CharField(max_length=255)),
                ('inspiration', models.TextField()),
                ('promotion_channels', models.JSONField()),
                ('student_reach', models.CharField(max_length=255)),
                ('consent', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campus_student',
            },
        ),
    ]
