# Generated by Django 5.2.10 on 2026-03-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_payments_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusstudent',
            name='campus_ambassador_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campusstudent',
            name='student_body_description',
            field=models.TextField(blank=True),
        ),
    ]
