# Generated by Django 5.2.10 on 2026-03-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_dossierdata_city_dossierdata_state'),
        ('students', '0004_campusstudent_campus_ambassador_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='dossier_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.dossierdata'),
        ),
    ]
