# Generated by Django 5.2.10 on 2026-03-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_payments_dossier_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='student',
        ),
    ]
