# Generated by Django 5.2.10 on 2026-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_contactus_options_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='application_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='slot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='slot_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
