# Generated by Django 5.2.10 on 2026-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentprofile_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_status',
            field=models.BooleanField(default=True),
        ),
    ]
