# Generated by Django 5.2.10 on 2026-03-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentprofile_gender'),
        ('students', '0011_studentprofile_profile_status'),
    ]

    operations = [
    ]
