# Generated by Django 5.2.10 on 2026-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_merge_20260309_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusstudent',
            name='campus_ambassador_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campusstudent',
            name='student_body_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
