# Generated by Django 5.2.10 on 2026-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_campusstudent_campus_ambassador_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='slot_update_count',
            field=models.IntegerField(default=0),
        ),
    ]
