# Generated by Django 5.2.10 on 2026-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_studentprofile_slot_update_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='signature',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
