# Generated by Django 5.2.10 on 2026-03-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_studentprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_medium',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_score_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='twelveth_medium',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='twelveth_score_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ug_score_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
