# Generated by Django 5.2.10 on 2026-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_studentprofile_tenth_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='tenth_medium',
            field=models.IntegerField(choices=[(1, 'ENGLISH'), (2, 'HINDI'), (3, 'OTHER')], default=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='twelveth_medium',
            field=models.IntegerField(choices=[(1, 'ENGLISH'), (2, 'HINDI'), (3, 'OTHER')], default=1),
        ),
    ]
