# Generated by Django 5.2.10 on 2026-03-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_studentprofile_tenth_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='application_id',
        ),
    ]
