# Generated by Django 5.2.10 on 2026-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_studentprofile_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mock_test_status',
            field=models.IntegerField(default=0),
        ),
    ]
