# Generated by Django 5.2.10 on 2026-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studentprofile_mock_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mock_test_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
