# Generated by Django 5.2.10 on 2026-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_alter_studentprofile_mock_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos')], default=1),
        ),
    ]
