# Generated by Django 5.2.10 on 2026-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_payments_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusstudent',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='campusstudent',
            name='mail_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
