# Generated by Django 5.2.10 on 2026-03-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_campusstudent_is_verified_campusstudent_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusstudent',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campusstudent',
            name='mail_status',
            field=models.BooleanField(default=False),
        ),
    ]
