# Generated by Django 5.2.10 on 2026-03-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_campusstudent_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusstudent',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
