# Generated by Django 5.2.10 on 2026-03-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_alter_payments_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='re_attempt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
