# Generated by Django 5.2.10 on 2026-03-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_studentprofile_re_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='re_attempt_btn',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
