# Generated by Django 5.2.10 on 2026-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_studentprofile_re_attempt_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='re_attempt_status',
            field=models.BooleanField(default=False),
        ),
    ]
