# Generated by Django 5.2.10 on 2026-03-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_payments_re_attempt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(blank=True, null=True)),
                ('slot_time', models.CharField(blank=True, max_length=200, null=True)),
                ('slot_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'User Slot Booking',
                'verbose_name_plural': 'User Slot Booking',
            },
        ),
    ]
