# Generated by Django 5.2.10 on 2026-03-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_studentslotbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'Vsl')], default=1, null=True),
        ),
    ]
