# Generated by Django 5.2.10 on 2026-04-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_alter_payments_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='application_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
