# Generated by Django 5.2.10 on 2026-04-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_studentprofile_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('testid', models.CharField(blank=True, max_length=250, null=True)),
                ('starttime', models.CharField(blank=True, max_length=250, null=True)),
                ('endtime', models.CharField(blank=True, max_length=250, null=True)),
                ('timetaken', models.CharField(blank=True, max_length=250, null=True)),
                ('totalscore', models.CharField(blank=True, max_length=250, null=True)),
                ('totalquestionsattempted', models.CharField(blank=True, max_length=250, null=True)),
                ('totalcorrectanswers', models.CharField(blank=True, max_length=250, null=True)),
                ('totalquestions', models.CharField(blank=True, max_length=250, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Exam Result',
                'verbose_name_plural': 'Student Exam Result',
            },
        ),
    ]
