# Generated by Django 5.2.10 on 2026-04-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_studentexamresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamresult',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
