# Generated by Django 5.2.10 on 2026-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_alter_studentexamresult_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='fee_waiver_category',
            field=models.CharField(default='No Waiver', max_length=200),
        ),
    ]
