# Generated by Django 5.2.10 on 2026-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_studentrealexamresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fee_waiver_category',
            field=models.CharField(default='No Waiver', max_length=200),
        ),
    ]
