# Generated by Django 5.2.10 on 2026-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_alter_payments_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='additional_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='additional_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_aadhaar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_agriculture_income',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_compute_income',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_employee_id_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_form16',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_income_tax_return',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_pan_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_passport_size',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_profession',
            field=models.IntegerField(blank=True, choices=[(1, 'SALARIED'), (2, 'SELFEMP'), (3, 'AGRICULTURE')], null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_sallary_slip',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_applicant_six_month_bank',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_fifth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_first_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_forth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_second_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_sixth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_third_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='twelth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
