# Generated by Django 5.2.10 on 2026-05-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_studentprofile_additional_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='accounting_profession',
            field=models.IntegerField(blank=True, choices=[(1, 'SELF'), (2, 'LOAN')], null=True),
        ),
    ]
