# Generated by Django 5.2.10 on 2026-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_studentprofile_accounting_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
