# Generated by Django 5.2.10 on 2026-05-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_exammasterkey_managemasterkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='managemasterkey',
            name='exam_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managemasterkey',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
