# Generated by Django 5.2.10 on 2026-05-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0046_managemasterkey_exam_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume_key_status',
            field=models.BooleanField(default=True),
        ),
    ]
