# Generated by Django 5.2.10 on 2026-05-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_studentprofile_resume_key_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managemasterkey',
            name='user',
        ),
        migrations.AddField(
            model_name='managemasterkey',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
