# Generated by Django 5.2.10 on 2026-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0048_remove_managemasterkey_user_managemasterkey_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='resume_key_status',
            field=models.BooleanField(default=False),
        ),
    ]
