# Generated by Django 5.2.10 on 2026-05-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_alter_studentprofile_resume_key_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_dropdown',
            field=models.IntegerField(blank=True, choices=[(0, 'SELECT'), (1, 'MOTHER'), (2, 'FATHER'), (3, 'OTHER')], null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_key_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_other_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
