# Generated by Django 5.2.10 on 2026-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0050_studentprofile_guardian_dropdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_key_status',
            field=models.BooleanField(default=False),
        ),
    ]
