# Generated by Django 5.2.10 on 2026-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_applicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlog',
            name='payload_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
