# Generated by Django 5.2.10 on 2026-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0053_applicationlog_payload_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='managemasterkey',
            name='reattempt_status',
            field=models.BooleanField(default=False),
        ),
    ]
