# Generated by Django 5.2.10 on 2026-06-05 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0054_managemasterkey_reattempt_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='accounting_profession',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='additional_document',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='additional_qualification',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_aadhaar',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_agriculture_income',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_compute_income',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_employee_id_card',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_form16',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_income_tax_return',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_pan_card',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_passport_size',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_profession',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_sallary_slip',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='co_applicant_six_month_bank',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_fifth_marksheet',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_first_marksheet',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_forth_marksheet',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_second_marksheet',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_sixth_marksheet',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_third_marksheet',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='identity_proof',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='tenth_marksheet',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='twelth_marksheet',
        ),
        migrations.CreateModel(
            name='StudentExperienceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'User Experience Draft',
                'verbose_name_plural': 'User Experience Draft',
            },
        ),
        migrations.CreateModel(
            name='StudentProfileDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], default=1)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tenth_passing_year', models.CharField(blank=True, max_length=255, null=True)),
                ('tenth_passing_percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('twelveth_passing_year', models.CharField(blank=True, max_length=255, null=True)),
                ('twelveth_passing_percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('medium_instruction', models.IntegerField(choices=[(1, 'ENGLISH'), (2, 'HINDI'), (3, 'OTHER')], default=1)),
                ('other_instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_status', models.IntegerField(choices=[(1, 'COMPLETED'), (2, 'PURSURING')], default=1)),
                ('pg_percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('higher_education_status', models.IntegerField(choices=[(1, 'YES'), (2, 'NO')], default=1)),
                ('higher_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('higher_qualification_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('employement_status', models.IntegerField(choices=[(1, 'FRESHER'), (2, 'EXPERIENCED')], default=1)),
                ('aadhaar', models.FileField(upload_to='')),
                ('dob_certificate', models.FileField(upload_to='')),
                ('photo', models.FileField(upload_to='')),
                ('signature', models.FileField(upload_to='')),
                ('profile_status', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_date', models.DateField(blank=True, null=True)),
                ('slot_time', models.CharField(blank=True, max_length=200, null=True)),
                ('slot_update_count', models.IntegerField(default=0)),
                ('tenth_score_type', models.CharField(blank=True, max_length=20, null=True)),
                ('tenth_medium', models.IntegerField(choices=[(1, 'ENGLISH'), (2, 'HINDI'), (3, 'OTHER')], default=1)),
                ('twelveth_score_type', models.CharField(blank=True, max_length=20, null=True)),
                ('twelveth_medium', models.IntegerField(choices=[(1, 'ENGLISH'), (2, 'HINDI'), (3, 'OTHER')], default=1)),
                ('ug_score_type', models.CharField(blank=True, max_length=20, null=True)),
                ('mock_test_status', models.IntegerField(default=0, null=True)),
                ('re_attempt', models.IntegerField(default=0, null=True)),
                ('re_attempt_btn', models.IntegerField(default=0, null=True)),
                ('application_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fee_waiver_category', models.CharField(default='No Waiver', max_length=200)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('resume_key_status', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_email', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_dropdown', models.IntegerField(blank=True, choices=[(0, 'SELECT'), (1, 'MOTHER'), (2, 'FATHER'), (3, 'OTHER')], null=True)),
                ('guardian_other_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_key_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile Draft',
                'verbose_name_plural': 'Student Profile Draft',
            },
        ),
    ]
