# Generated by Django 5.2.10 on 2026-06-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_remove_studentprofile_accounting_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexperiencedraft',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofiledraft'),
        ),
    ]
