# Generated by Django 5.2.10 on 2026-06-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_alter_studentexperiencedraft_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Master',
                'verbose_name_plural': 'Company Master',
            },
        ),
        migrations.CreateModel(
            name='ManageStudentInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_status', models.IntegerField(blank=True, choices=[(1, 'Present'), (2, 'Absent')], null=True)),
                ('absent_reason', models.TextField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, choices=[(1, 'Selected'), (2, 'Not Selected')], null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.companymaster')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Manage Master Key',
                'verbose_name_plural': 'Manage Master Key',
            },
        ),
    ]
