# Generated by Django 5.2.10 on 2026-06-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0057_companymaster_managestudentinterview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managestudentinterview',
            options={'verbose_name': 'Manage Student Interview', 'verbose_name_plural': 'Manage Student Interview'},
        ),
    ]
