# Generated by Django 5.2.10 on 2026-06-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0058_alter_managestudentinterview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='managestudentinterview',
            name='package_status',
            field=models.BooleanField(default=False),
        ),
    ]
