# Generated by Django 5.2.10 on 2026-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0060_studentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='managestudentinterview',
            name='payment_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='managestudentinterview',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
