# Generated by Django 5.2.10 on 2026-06-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0061_managestudentinterview_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofiledraft',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], default=1, null=True),
        ),
    ]
