# Generated by Django 5.2.10 on 2026-07-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0063_managestudentinterviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='managestudentinterviewhistory',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
