# Generated by Django 5.2.10 on 2026-07-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0068_alter_payments_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'VslOptin'), (13, 'VslFinal'), (14, 'ARC'), (15, 'Affiliate7'), (16, 'CPA'), (17, 'EA'), (18, 'EAWebsite'), (19, 'CPAWebsite'), (20, 'EALPCampaign'), (21, 'CPALPCampaign')], default=1, null=True),
        ),
    ]
