"""
Django settings for gcc_backend project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import json
from datetime import timedelta
from google.oauth2 import service_account
from google.cloud import storage

env = environ.Env()
environ.Env.read_env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sh6i0o%#lp7$%1y&_mb($z@g1jm^)%_*$d*+4&=&s_-gnu8u@p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    # 'drf_standardized_errors',
    'users',
    'students',
    'career',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gcc_backend.urls'

AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.hostinger.com'
# EMAIL_HOST_USER = 'kamalchhabra@kcglobed.com'
# EMAIL_HOST_PASSWORD = '@Dud40354'
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True



WSGI_APPLICATION = 'gcc_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    os.getenv("CSRF_TRUSTED_ORIGINS")
]


os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = os.path.join(
    BASE_DIR, os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
)


STORAGES = {
    "default": {
        "BACKEND": 'gcc_backend.gcloud.Media',
    },
    "staticfiles": {
        "BACKEND": 'gcc_backend.gcloud.Static',
    },
}
GS_PROJECT_ID = os.getenv("GS_PROJECT_ID")
GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME")
GS_BUCKET_NAME_2 = os.getenv("GS_BUCKET_NAME_2")
GS_STATIC_BUCKET_NAME = os.getenv("GS_STATIC_BUCKET_NAME")
GS_FILE_OVERWRITE = False
MEDIA_ROOT = "media/"
STATIC_ROOT = "static/"
STATIC_URL = 'https://storage.googleapis.com/{}/static/'.format(GS_STATIC_BUCKET_NAME)
MEDIA_URL = 'https://storage.googleapis.com/{}/media/'.format(GS_BUCKET_NAME)
SECURE_MEDIA_URL = 'https://storage.googleapis.com/{}/media/'.format(GS_BUCKET_NAME_2)

SIGNED_URL_EXPIRY = int(os.getenv("SIGNED_URL_EXPIRY")) #minutes

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
       'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 'DEFAULT_PAGINATION_CLASS': 'gcc_backend.pagination.CustomPageNumberPagination',
    # "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    # 'PAGE_SIZE': 20,
}


# DRF_STANDARDIZED_ERRORS = {
#     "EXCEPTION_FORMATTER_CLASS": "gcc_backend.exception_formatter.CustomExceptionFormatter",
# }


ACCESS_TIME_FORMAT=os.getenv("ACCESS_TIME_FORMAT")
ACCESS_TIME=os.getenv("ACCESS_TIME")
REFRESH_TIME_FORMAT=os.getenv("REFRESH_TIME_FORMAT")
REFRESH_TIME=os.getenv("REFRESH_TIME")


# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(ACCESS_TIME_FORMAT=ACCESS_TIME),
#     "REFRESH_TOKEN_LIFETIME": timedelta(REFRESH_TIME_FORMAT=REFRESH_TIME),
#     "AUTH_HEADER_TYPES": ("Bearer",),
# }

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=40),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=59),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv("EMAIL_HOST")
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'info@gccschool.com'
EMAIL_HOST_PASSWORD = 'KCglobed@123'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# BASE_URL = 'https://gccschool.com'
WEBSITE_BASE_URL = os.getenv("WEBSITE_BASE_URL")
