# Generated by Django 5.2.10 on 2026-04-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('thumbnailImage', models.FileField(blank=True, null=True, upload_to='blog/seminar_thumbnail/images/')),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('event_link', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manage Seminar',
                'verbose_name_plural': 'Manage Seminar',
            },
        ),
    ]
