# Generated by Django 5.2.10 on 2026-04-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_manageseminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageseminar',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
