# Generated by Django 5.2.10 on 2026-04-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_manageseminar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageseminar',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
