# Generated by Django 5.2.10 on 2026-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_manageseminar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='altImage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
