# Generated by Django 5.2.10 on 2026-02-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('highest_qualification', models.CharField(max_length=255)),
                ('employment_status', models.CharField(max_length=255)),
                ('experience_years', models.CharField(max_length=50)),
                ('area_of_interest', models.CharField(max_length=255)),
                ('area_of_interest_other', models.CharField(blank=True, max_length=255, null=True)),
                ('contribution_summary', models.TextField(blank=True, null=True)),
                ('resume_path', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_period', models.CharField(max_length=50)),
                ('consent', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'career_application',
            },
        ),
        migrations.CreateModel(
            name='PartnerWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('year_of_establishment', models.CharField(max_length=10)),
                ('organization_type', models.CharField(max_length=255)),
                ('organization_type_other', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('interests', models.JSONField()),
                ('description', models.TextField()),
                ('value_add', models.TextField()),
                ('declaration', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partner_with_us',
            },
        ),
    ]
