# Generated by Django 5.2.10 on 2026-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_dossierdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
