# Generated by Django 5.2.10 on 2026-03-13 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_supportform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supportform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supportform',
            name='phone',
        ),
        migrations.AddField(
            model_name='supportform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
