# Generated by Django 5.2.10 on 2026-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_remove_supportform_email_remove_supportform_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos')], default=1),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='source_form',
            field=models.IntegerField(choices=[(1, 'ApplyNow'), (2, 'Dossier'), (3, 'Program')], default=1),
        ),
    ]
