# Generated by Django 5.2.10 on 2026-03-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_dossierdata_source_dossierdata_source_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierdata',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5')], default=1),
        ),
    ]
