# Generated by Django 5.2.10 on 2026-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_alter_dossierdata_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='degree_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
