# Generated by Django 5.2.10 on 2026-04-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_alter_dossierdata_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='VslDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_playback', models.IntegerField(default=0)),
                ('specialist_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.dossierdata')),
            ],
        ),
    ]
