# Generated by Django 5.2.10 on 2026-04-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0012_dossierdata_ad_id_dossierdata_ad_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierAbondant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'VslOptin'), (13, 'VslFinal')], default=1)),
                ('source_form', models.IntegerField(choices=[(1, 'ApplyNow'), (2, 'Dossier'), (3, 'Program')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
