# Generated by Django 5.2.10 on 2026-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0014_dossierdata_university_dossierdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='document_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='remarks_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
