# Generated by Django 5.2.10 on 2026-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_dossierdata_document_status_dossierdata_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierdata',
            name='ad_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='ad_source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='adset_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='fbc_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='fbclid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='university',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='utm_adname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='utm_content',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='utm_source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
