# Generated by Django 5.2.10 on 2026-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0016_alter_dossierdata_ad_id_alter_dossierdata_ad_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierabondant',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierabondant',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierabondant',
            name='utm_source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
