# Generated by Django 5.2.10 on 2026-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0017_dossierabondant_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='fee_waiver_category',
            field=models.CharField(default='No Waiver', max_length=200),
        ),
    ]
