# Generated by Django 5.2.10 on 2026-04-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0018_dossierdata_fee_waiver_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierdata',
            name='fee_waiver_category',
        ),
    ]
