# Generated by Django 5.2.10 on 2026-04-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0019_remove_dossierdata_fee_waiver_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='fee_waiver_category',
            field=models.CharField(default='No Waiver', max_length=200),
        ),
    ]
