# Generated by Django 5.2.10 on 2026-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0020_dossierdata_fee_waiver_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='referred_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
