# Generated by Django 5.2.10 on 2026-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0021_dossierdata_referred_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
