# Generated by Django 5.2.10 on 2026-05-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0023_alter_dossierabondant_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierabondant',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'VslOptin'), (13, 'VslFinal'), (14, 'Affiliate6')], default=1),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'VslOptin'), (13, 'VslFinal'), (14, 'Affiliate6')], default=1),
        ),
    ]
