# Generated by Django 5.2.10 on 2026-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0025_dossierlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierlog',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
