# Generated by Django 5.2.10 on 2026-05-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0026_dossierlog_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierlog',
            name='datas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
