# Generated by Django 5.2.10 on 2026-07-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0028_alter_dossierabondant_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
