# Generated by Django 5.2.10 on 2026-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0030_alter_dossierabondant_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='program',
            field=models.IntegerField(blank=True, choices=[(1, 'CPA'), (2, 'EA')], null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='reffered_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
