# Generated by Django 5.2.10 on 2026-07-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0032_alter_dossierabondant_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='age_range',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='attend_from',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='fund_mode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
