# Generated by Django 5.2.10 on 2026-07-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0033_dossierdata_age_range_dossierdata_attend_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierabondant',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'VslOptin'), (13, 'VslFinal'), (14, 'Affiliate6'), (15, 'Affiliate7'), (16, 'CPA'), (17, 'EA'), (18, 'EAWebsite'), (19, 'CPAWebsite')], default=1),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'VslOptin'), (13, 'VslFinal'), (14, 'Affiliate6'), (15, 'Affiliate7'), (16, 'CPA'), (17, 'EA'), (18, 'EAWebsite'), (19, 'CPAWebsite')], default=1),
        ),
    ]
