# Generated by Django 5.2.10 on 2026-08-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0037_dossierdata_child_email_dossierdata_child_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='slot_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
