# Generated by Django 5.2.10 on 2026-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0038_dossierdata_slot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='speak_with',
            field=models.IntegerField(blank=True, choices=[(1, 'Kamal'), (2, 'Nitish')], null=True),
        ),
    ]
