# Generated by Django 5.2.10 on 2026-08-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0039_dossierdata_speak_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='social_url',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
