# Generated by Django 5.2.10 on 2026-08-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0041_managedossiermeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedossiermeeting',
            name='cancel_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='managedossiermeeting',
            name='reschedule_status',
            field=models.BooleanField(default=False),
        ),
    ]
