# Generated by Django 5.2.10 on 2026-08-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0042_alter_managedossiermeeting_cancel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMeetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('join_url', models.CharField(blank=True, max_length=200, null=True)),
                ('host_url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetinglog', to='career.dossierdata')),
            ],
        ),
    ]
