# Generated by Django 5.2.10 on 2026-08-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0043_dossiermeetinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermeetinglog',
            name='host_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossiermeetinglog',
            name='join_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managedossiermeeting',
            name='host_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managedossiermeeting',
            name='join_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
