# Generated by Django 5.2.10 on 2026-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0044_alter_dossiermeetinglog_host_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='preffer_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
