# Generated by Django 5.2.10 on 2026-08-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0045_dossierdata_preffer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierdata',
            name='program',
            field=models.IntegerField(blank=True, choices=[(1, 'CPA'), (2, 'EA'), (3, 'ACCA')], null=True),
        ),
    ]
