# Generated by Django 5.2.10 on 2026-09-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0046_alter_dossierdata_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='annual_enrollments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='business_setup',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='experience',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='organization',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='promotes_certifications',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='student_category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dossierabondant',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'VslOptin'), (13, 'VslFinal'), (14, 'Affiliate6'), (15, 'Affiliate7'), (16, 'CPA'), (17, 'EA'), (18, 'EAWebsite'), (19, 'CPAWebsite'), (20, 'EALPCampaign'), (21, 'CPALPCampaign'), (22, 'EALPRudrapur'), (23, 'Affliate8'), (24, 'Partner')], default=1),
        ),
        migrations.AlterField(
            model_name='dossierdata',
            name='source',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Efos'), (3, 'Affiliate1'), (4, 'Affiliate2'), (5, 'Affiliate3'), (6, 'Affiliate4'), (7, 'Affiliate5'), (8, 'IPUniversity'), (9, 'DelhiUniversity'), (10, 'CCS'), (11, 'Kuk'), (12, 'VslOptin'), (13, 'VslFinal'), (14, 'Affiliate6'), (15, 'Affiliate7'), (16, 'CPA'), (17, 'EA'), (18, 'EAWebsite'), (19, 'CPAWebsite'), (20, 'EALPCampaign'), (21, 'CPALPCampaign'), (22, 'EALPRudrapur'), (23, 'Affliate8'), (24, 'Partner')], default=1),
        ),
    ]
