# Generated by Django 5.2.10 on 2026-09-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0047_dossierdata_annual_enrollments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierdata',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='career/file/'),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='other_category_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossierdata',
            name='other_certificate_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
